Features: &Features
  feature_object_identifier_name: &feature_object_identifier_name "object_identifier"
  default_object_identifier: &default_object_identifier
    *feature_object_identifier_name:
      name: *feature_object_identifier_name
      classes_fname: "model_data/coco_classes.txt"
      threshold: 0.9
      gpu_face: 0.8
      model: "pydarknet"
      class_filters: ["person"]
      feature_on: No

  feature_face_recognizer_name: &feature_face_recognizer_name "face_recognizer"
  default_face_recognizer: &default_face_recognizer
    name: *feature_face_recognizer_name
    draw: Yes
    show_all_labels: No
    face_id_threshold: 0.9
    face_id_gpu_frac: 0.5
    face_detector_gpu_frac: 0.5

DataSink: &DataSink
  base_output_path: &base_output_path "~/.output/face-id/"
  s3sync: &s3sync
    output_path: *base_output_path
    error_files_dir: "~/.output/face-id/sync-service/error-files"
    spool_path: "~/.output/face-id/spool"
    backup_path: "~/.output/face-id/backup"
    s3_bucket_name: ""
  metadata_saver: &metadata_saver
    dbname: "dbname"
    user: "apilona"

<<: *default_object_identifier
Feeds: &Feeds
  face_recognizer_feed:
    feed_pipeline_type: "FaceRecognizerFeed"
    feed_type: "webcam"
    source: 0
    save_raw_video: Yes
    save_proc_video: Yes
    save_metadata: Yes
    features:
      *feature_face_recognizer_name:
        name: "face_recognizer_demo"
        depends_on: "none"
        settings:
          draw: Yes
          show_all_labels: No
          face_id_threshold: 0.65
          face_id_gpu_frac: 0.1
          face_detector_gpu_frac: 0.25

    data_sink:
      <<: *s3sync
      <<: *metadata_saver
